Assets/Scripts/UI/TabbedMenu.cs
=> Singleton!

Assets/Prefabs/NPCs/Robot.prefab, Assets/Prefabs/NPCs/SampleNpc.prefab, Assets/Scenes/NpcTesting.unity, Assets/Scenes/NpcTesting.unity.meta, Assets/Scripts/NpcBehaviors/BaseNpc.cs, Assets/Scripts/NpcBehaviors/NpcTesting.cs, Assets/Scripts/NpcBehaviors/NpcTesting.cs.meta, Assets/Scripts/NpcBehaviors/RobotNpc.cs, Assets/Scripts/NpcEvents/UnlockDoors.asset, Assets/Scripts/NpcEvents/UnlockDoors.asset.meta
Set up the Robot NPC prefab with all its dialogue and logic flow.
Also created a NpcTesting scene with the Robot to demonstrate how its dialogue transitions function.
Documentation: https://docs.google.com/document/d/1EnqM_5lMTHVfaAcLzAhTvpqqEmj9KwIhnKPfB2Cj65c/edit
=> Merging Robot NPC

Assets/Prefabs/NPCs/Coward.prefab, Assets/Prefabs/NPCs/Coward.prefab.meta, Assets/Prefabs/NPCs/GeneratorRoomTrigger.prefab, Assets/Prefabs/NPCs/GeneratorRoomTrigger.prefab.meta, Assets/Prefabs/NPCs/Robot.prefab, Assets/Scenes/NpcTesting.unity, Assets/Scripts/NpcBehaviors/BaseNpc.cs, Assets/Scripts/NpcBehaviors/CowardNpc.cs, Assets/Scripts/NpcBehaviors/CowardNpc.cs.meta, Assets/Scripts/NpcBehaviors/NpcTesting.cs, Assets/Scripts/NpcBehaviors/RobotNpc.cs, Assets/Scripts/NpcBehaviors/SampleNpc.cs, Assets/Scripts/NpcEvents/GeneratorRoomCheck.cs, Assets/Scripts/NpcEvents/GeneratorRoomCheck.cs.meta, Assets/Scripts/NpcEvents/OnEnterRoom.asset, Assets/Scripts/NpcEvents/OnEnterRoom.asset.meta
https://docs.google.com/document/d/1EnqM_5lMTHVfaAcLzAhTvpqqEmj9KwIhnKPfB2Cj65c/edit
Added coward and made minor improvements to dialogue flow.
Can test Coward NPC in NpcTesting scene.
=> Coward NPC, Generator Room Trigger, Minor NPC Tweaks

Assets/Scripts/InventoryScripts/InventoryHolder.cs, Assets/Scripts/InventoryScripts/InventorySlot.cs, Assets/Scripts/InventoryScripts/InventorySystem.cs, Assets/Scripts/InventoryScripts/Pickupable.cs
Expanded AddToInventory and RemoveFromInventory. Added some safety nets for edge test cases. 
Add: 
Now returns any not-added items; i.e. "overflow", if another script so desires. 
Fires event with proper parameters that lets other scripts know stuff was added to the inventory
Remove:
All functionality needed was added. Callers can specify if they want the remove to be unchecked or checked (as if a store is checking if the inventory has the required items), what to remove, how much, and receive what was removed and how much.
Fires event with proper parameters that lets other scripts know stuff was removed from the inventory
Fixed the Pickupable script to ignore returned amount.
=> Inventory system fix

Assets/Prefabs/Minigames/Wire/Wire.prefab, Assets/Prefabs/NPCs/Coward.prefab, Assets/Prefabs/NPCs/GeneratorRoomTrigger.prefab, Assets/Prefabs/NPCs/NpcTesting.prefab, Assets/Prefabs/NPCs/NpcTesting.prefab.meta, Assets/Prefabs/NPCs/Robot.prefab, Assets/Prefabs/NPCs/SampleNpc.prefab, Assets/Scripts/Minigames/WireGame/MGTestingScript.cs, Assets/Scripts/NpcBehaviors/BaseNpc.cs, Assets/Scripts/NpcBehaviors/CowardNpc.cs, Assets/Scripts/NpcBehaviors/NpcTesting.cs, Assets/Scripts/NpcEvents/GeneratorRoomCheck.cs, Assets/Scripts/NpcEvents/NpcEvent.cs, Assets/Scripts/NpcEvents/NpcEventListener.cs
Documentation: https://docs.google.com/document/d/12epA9t3Q7tPEW9BuULWT7HR05d8T7iwK1qOIbjGotrQ/edit
- Gave NpcEvent an enum for event tag comparisons rather than a string.
- Created a struct in NpcEventListener to allow one listener to listen for multiple different events.
- Updated any prefabs that currently use the event system.
- Also updated any scripts that trigger events.
=> Merging Event System Cleanup

.idea/.idea.Placebo-Entertainment/.idea/workspace.xml, Assets/Materials.meta, Assets/Prefabs/UI/TabbedMenu.prefab, Assets/Scripts/NpcBehaviors/BaseNpc.cs, Assets/Scripts/UI/TabbedMenu.cs, Assets/UI Toolkit/Dialogue/Dialogue.uxml, Assets/UI Toolkit/Dialogue/DialogueOption.uxml, Assets/UI Toolkit/Dialogue/DialogueOption.uxml.meta
Changes were just re-organizing and swapping the hardcoded npc based dialogue entries to just having actions that get invoked.
=> Dialogue cleanup

.idea/.idea.Placebo-Entertainment/.idea/workspace.xml, Assets/Prefabs/UI/TabbedMenu.prefab, Assets/Scripts/UI/TabbedMenu.cs, Assets/UI Toolkit/Crosshair.meta, Assets/UI Toolkit/Crosshair/Crosshair.uxml, Assets/UI Toolkit/Crosshair/Crosshair.uxml.meta
Adds a crosshair to the game, enabled by default, and sorted lower in order to be obscured by other UI elements.
=> Add a crosshair.

Assets/Scripts/InventoryScripts/Pickupable.cs
https://discord.com/channels/1237040972920262756/1250615917725876276/1250969396067700806
=> Pickups Disappear Once Collected

Assets/Prefabs/Fullplayer.prefab, Assets/Prefabs/Minigames/CowardMinigame/ActualWrench.prefab, Assets/Scenes/Level/CowardMinigame.unity, Assets/Scenes/Level/GreyBoxing.unity
=> Coward minigame bugfixed

Assets/Prefabs/Minigames/Wire/Wire.prefab, Assets/Scripts/Minigames/WireGame/MGWire.cs
https://discord.com/channels/1237040972920262756/1250615917725876276/1250969396067700806
=> Hardcoded wires to have the shader

Assets/Prefabs/NPCs/Angel.prefab, Assets/Prefabs/NPCs/Coward.prefab, Assets/Scripts/NpcBehaviors/BaseNpc.cs, Assets/Scripts/NpcBehaviors/CowardNpc.cs, Assets/Scripts/Player/PlayerController.cs
https://discord.com/channels/1237040972920262756/1250615917725876276/1250968997726388234
Cleaned up the Coward and light bulb interaction prompts so they shouldn't overlap. Note: the Coward talking to you when you pick the light bulb up is an intentional behavior. 
Additionally, the player can no longer interact, move, or look when engaging in dialogue.
=> Interaction bugs

Assets/Prefabs/ItemsAndBypassers/ScriptableObjects/RobotBypass.asset, Assets/Prefabs/ItemsAndBypassers/ScriptableObjects/Wrench.asset, Assets/Scripts/InventoryScripts/InventoryHolder.cs, Assets/Scripts/Loop/LoopController.cs
[Card](https://board.placeboentertainment.com/b/Yk6XSG76skkvdcuox/engine-team/8nm69Pf9rsqQE9ABw)
The recalibration tool should now save across loops and allow you to skip the robot game.
=> Fixed Recalibration tool bug

Assets/Scenes/Level/GreyBoxing.unity
The Angel minigame was added to the Greyboxing level
=> Angel minigame added

Assets/Scripts/NpcBehaviors/CowardNpc.cs
added one line of code to add the wrench to the inventory. I tested it and it carries through the loops
=> Wrench fix

Assets/Prefabs/Fullplayer.prefab, Assets/Scenes/Level/GreyBoxing.unity, Assets/Scripts/Interaction Box/InteractionDemo.cs, Assets/Scripts/Minigames/CowardMiniGame/RipcordBehavior.cs, Assets/Scripts/Player/PlayerController.cs
Card[https://board.placeboentertainment.com/b/Yk6XSG76skkvdcuox/engine-team/mthcghQKWvGj7qYbJ](url)
Updated player movement to no longer move the rigidbody.
=> Updated Player Movement/Collision

Assets/Prefabs/NPCs/Angel.prefab, Assets/Prefabs/NPCs/Coward.prefab, Assets/Prefabs/SaveLoadManager.prefab, Assets/Scenes/Level/GreyBoxing.unity, Assets/Scripts/NpcEvents/GameWon.asset, Assets/Scripts/NpcEvents/GameWon.asset.meta, Assets/Scripts/NpcEvents/NpcEvent.cs
Game should fully reset on win
=> Game win reset

Assets/Scenes/Level/FireMinigame.unity, Assets/Scripts/Minigames/FireMiniGame/FishBehavior.cs
review within greybox or fish scene small fix to a big problem
=> Left click bug fish

Assets/UI Toolkit/Dialogue/Dialogue.uxml, Assets/UI Toolkit/Dialogue/DialogueOption.uxml
Card[https://board.placeboentertainment.com/b/Yk6XSG76skkvdcuox/engine-team/eSjSdkubz4joA8Jyt](url)
Updated the size of the NPC dialogue box and the player response buttons to contain larger amounts of text.
=> Dialogue size bug

Assets/Scenes/Level/GreyBoxing.unity, Assets/Scripts/Minigames/FireMiniGame/FishBehavior.cs
the fish when it activates minigame no longer has two fish out. play the game as normal in the greybox scene and just make sure for me.
=> fish no longer in two places

Assets/Scripts/UI/TabbedMenu.cs, Assets/UI Toolkit/TabbedMenu/TabbedMenu.uxml
No new documentation
The contents of the tabbed menu no longer appear when clicking tab. Instead, a clock will show up that counts up from 0 seconds and resets when the scene reloads.
=> Removed Tab Menu + Added Dev Timer

Assets/Scenes/MainMenuScene.unity, Assets/Scenes/MainMenuScene.unity.meta, Assets/Scripts/UI/MainMenu.cs, Assets/Scripts/UI/MainMenu.cs.meta, Assets/UI Toolkit/Menus.meta, Assets/UI Toolkit/Menus/MainMenu.uxml, Assets/UI Toolkit/Menus/MainMenu.uxml.meta, Assets/UI Toolkit/Menus/MainMenuStyle.uss, Assets/UI Toolkit/Menus/MainMenuStyle.uss.meta, ProjectSettings/EditorBuildSettings.asset
Documentation: https://docs.google.com/document/d/1ydBjNoP09OcftJOvyShO_Gb-3rIgRBvGuSVhkGAXwo8/edit
The main menu scene has been set up with a functional main menu. The Start Game button should load the intro slideshow scene. The Settings and Credits buttons will open submenus. Each of those submenus has a Back button that will return to the main menu. Finally, there is an Exit Game button that calls Application.Quit().
=> Main menu functionality

Assets/Scripts/UI/TabbedMenu.cs, Assets/UI Toolkit/Dialogue/Dialogue.uxml, Assets/UI Toolkit/Dialogue/DialogueOption.uxml
All dialogue text now has a bit more padding around the edges. All dialogue text no longer auto-scales and instead will remain a constant size. Finally, the buttons for player responses can now automatically grow vertically as needed to ensure that all the text can fit.
=> Dialogue UI updates

Assets/Scripts/Minigames/FireMiniGame/FireBehavior.cs
one script fix for immediate shrinkage best tested in scene
=> shrinkage added

Assets/Prefabs/Minigames/CowardMinigame/Ripcord.prefab, Assets/Scenes/GameScene.unity
Edited events on the Coward and ripcord to make that quest able to be completed.
=> Fixed Coward Softlock

Assets/Scenes/GameScene.unity
The waterspray of the fish was not lined up properly, so now it should look much better
=> Super minor update to the waterspray on the Fish

Assets/Prefabs/LoopController.prefab, Assets/Scenes/GameScene.unity, Assets/Scenes/TestGyms/AngelMini.unity, Assets/Scenes/TestGyms/RobotMini.unity
Mainly focused on the angel scene. To fix the error I applied the overrides to the LoopController prefab in main gamescene and made sure they carried over to the LC prefab in the angel scene. 
The printout that says the timer does not exist only occurs once, as TabbedMenu tries to get the Timer before LC makes it in start. Nick G was the one made a fail safe for it in update, I believe. Hopefully I will be able to get ride of LC soon so we dont have to see that all the time.
=> Fixed Timer bug in TestGyms

Assets/Scripts/Player/PlayerController.cs
[Card](https://board.placeboentertainment.com/b/Yk6XSG76skkvdcuox/engine-team/RFo8RmcGHpEaFKCCE)
Footprints no longer stop showing up after standing still for several seconds. Also, fixed the errors that were being thrown when ending your movement on a second loop.
=> Fixed Footprint Bug

Assets/Prefabs/NPCs/Fish.prefab, Assets/Scenes/GameScene.unity, Packages/manifest.json, Packages/packages-lock.json
no code just test on second loop if fish teleports like on first loop
=> fish teleport on next loop

Assets/Prefabs/NPCs/Angel.prefab, Assets/Prefabs/NPCs/Coward.prefab, Assets/Prefabs/NPCs/Fish.prefab, Assets/Prefabs/NPCs/Goop.prefab, Assets/Prefabs/NPCs/Robot.prefab
All NPC name fields have been changed within their respective prefabs, so the character dialogue reflects their actual names
=> Changed NPC Names

Assets/Prefabs/Minigames/CowardMinigame/GeneratorMinigame.prefab, Assets/Scenes/GameScene.unity, Assets/Scenes/TestGyms/GeneratorMini.unity, Assets/Scripts/Minigames/CowardMiniGame/GeneratorDemoStart.cs, Assets/Scripts/Minigames/CowardMiniGame/LightManager.cs, Assets/Scripts/Minigames/CowardMiniGame/RipcordBehavior.cs
added two serilaized felds on the light manager to pick the idle and correct colors for the lights. Added a function to change the color of the lights. Edited scripts to change how the blinking works
=> Ripcord light changes

Assets/Art/Models/Coward/animations/Coward_AnimController.controller, Assets/Scripts/NpcBehaviors/CowardNpc.cs
=> Coward anims are in!

Assets/Scenes/GameScene.unity
White boards are in the:
- Generator room
- Angel room or bridge
- Robot room
- Hallway just before the fire room
=> Added in the initial whiteboards

Assets/Scripts/Player/PlayerController.cs, Assets/Scripts/UI/TabbedMenu.cs
Pressing R or Shift will still work in editor, but won't work when in a build.
=> Dev Tools Only Work in Editor

Assets/Prefabs/NPCs/Angel.prefab, Assets/Prefabs/NPCs/Coward.prefab, Assets/Prefabs/NPCs/Fish.prefab, Assets/Prefabs/TimerManager.prefab, Assets/Scripts/NpcBehaviors/AngelNpc.cs
I was testing in main and found that the coward and fish npcs were missing a reference to the event that disables the death timers. So I added those in and then also set up the Angel to end the loop timer.
=> added timer event to npc prefabs and added final loop timer for angel

Assets/Prefabs/Fullplayer.prefab, Assets/Scenes/GameScene.unity, Assets/Scripts/Player/PlayerController.cs
Quickly modified the player's starting position in main scene to address the "falling from air" mini bug.
=> PlayerHeightAdjustment

Assets/Scripts/UI/MainMenu.cs
The MainMenu script now correctly references the static instance of SaveLoadManager to ensure that saved data is actually being deleted.
=> New Game Button Clears Saved Data

Assets/UI Toolkit/Menus/MainMenu.uxml, Assets/UI Toolkit/Menus/PauseMenu.uxml
Moved all of the sliders to be closer to their respective headers.
=> Settings Padding Changed

Assets/Scripts/Audio/AudioManager.cs
Implemented by adding an NPC Event Listener & AudioManager to the main game scene. The listener invokes a stop/start loop music whenever the key events for showing the final countdown display occur. See the AudioManager gameObject for more details.
=> Re-Implement Music Playback

Assets/UI Toolkit/LoopEndScreen/AlarmClockStyle.uss
Timer moves closer to the center of the screen instead of the top third.
=> Moved Death Timer to Center

Assets/Prefabs/NPCs/Coward.prefab
- Added dialogue for the player's response when the lightbulb has not been picked up
=> Fixed Coward dialogue break

Assets/Prefabs/Fullplayer.prefab, Assets/Scripts/Player/PlayerControls.cs, Assets/Scripts/Player/PlayerControls.inputactions
You can move, interact with objects, and toggle the pause menu. Pretty much everything that isn't menuing.
=> Added Movement and Gameplay Inputs

Assets/Scripts/UI/MainMenu.cs, Assets/Scripts/UI/PauseMenu.cs
The sliders move more smoothly when using a controller
=> Slider sens tuning

.idea/.idea.Placebo-Entertainment/.idea/workspace.xml, Assets/Prefabs/Fullplayer.prefab
- Changed vertical and horizontal cinemachine accel and decel to 0.05
- Lowered minimum sens to 75
- Lowered max sens to 350
=> Sensitivity is no longer floaty

Assets/Prefabs/ItemsAndBypassers/Lightbulb.prefab, Assets/Prefabs/ItemsAndBypassers/TranslationBook.prefab, Assets/Prefabs/Minigames/FireMiniGame/HoseAndWater.prefab, Assets/Prefabs/NPCs/Coward.prefab
Changing coward to Odon in *Pet the Coward*
=> Singular dialogue change

Assets/Scripts/Loop/LoopController.cs, Assets/Scripts/UI/TabbedMenu.cs
Black screen with clock should last longer and is now adjustable
=> Loop delay

Assets/Scripts/Loop/LoopController.cs, Assets/Scripts/Loop/Timer.cs, Assets/Scripts/NpcBehaviors/AngelNpc.cs, Assets/Scripts/NpcBehaviors/BaseNpc.cs, Assets/Scripts/Player/PlayerController.cs, Assets/Scripts/UI/MonologueManager.cs
There were also slight window changes to cover up or uncover things
=> Fixed steam achievements breaking fuse build
